deployment:
  image: 838180513114.dkr.ecr.us-east-1.amazonaws.com/roboshop/frontend

  # Jenkins should override this dynamically
  imageVersion: "1.0.0"

  targetPort: 80

  replicas: 2

service:
  port: 80

ingress:
  host: roboshop.hellodevsecops.space

  groupName: roboshop-ingress

  certificateArn: arn:aws:acm:us-east-1:838180513114:certificate/4a046129-225d-41d8-bad9-021ca1c3bcb0

hpa:
  maxReplicas: 10
  utilisation: 75